name: Feature Request
description: Suggest a new feature
labels: ["enhancement"]
body:
  - type: textarea
    attributes:
      label: Description
    validations:
      required: true
  - type: input
    attributes:
      label: Community forum reference
      description: If this feature was already discussed on the Community Forum link it here
      placeholder: https://community.nodebb.org/topic/0/example-feature-request