name: Feature request
description: Suggest an idea
labels: ["enhancement"]
body:
  - type: textarea
    attributes:
      name: Description
  - type: input
    attributes:
      name: Community forum reference
      description: If this feature was already discussed on the Community Forum link it here
      placeholder: https://community.nodebb.org/topic/0/example-feature-request